//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODERN_GUI_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APCORREO
    {
        public int ID { get; set; }
        public int EMPRESA { get; set; }
        public string CORREO { get; set; }
        public string CLAVE { get; set; }
        public string NOMBRECORREO { get; set; }
        public string HOST { get; set; }
        public int PUERTO { get; set; }
        public string ASUNTO { get; set; }
        public string MENSAJE { get; set; }
        public string PAGINAWEB { get; set; }
    
        public virtual APEMPRESA APEMPRESA { get; set; }
    }
}
