//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODERN_GUI_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APNCRCAB
    {
        public decimal ID { get; set; }
        public int EMPRESA { get; set; }
        public int SUCURSAL { get; set; }
        public string SERIE { get; set; }
        public long NUMERO { get; set; }
        public double SUBTOTALNCR { get; set; }
        public double DESCUENTONCR { get; set; }
        public double IVAFAC { get; set; }
        public double NETOFAC { get; set; }
        public System.DateTime FECHAEMI { get; set; }
        public System.DateTime FECHADOC { get; set; }
        public string RUC { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONOS { get; set; }
        public string CORREO { get; set; }
        public string SERIEFAC { get; set; }
        public string NUMEROFAC { get; set; }
        public string CLAVEACCESO { get; set; }
        public string OBSERVACION { get; set; }
        public string NOAUTORIZACION { get; set; }
        public string ARCHIVOSOLO { get; set; }
        public string ARCHIVOFIRMA { get; set; }
        public string ARCHIVOAUTORIZACION { get; set; }
        public string ARCHIVOPDF { get; set; }
        public string ARCHIVOERROR { get; set; }
        public string CONCEPTOERROR { get; set; }
        public string CODIGOERROR { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public string HORAREGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAPROCESO { get; set; }
        public string HORAPROCESO { get; set; }
        public string ESTADOPROCESO { get; set; }
        public string TIPO { get; set; }
        public string SUBIDOALAWEB { get; set; }
        public string ACTUALIZADOSC { get; set; }
        public string CODCLIENTE { get; set; }
        public string NombreDocumento { get; set; }
        public string CLAVE { get; set; }
        public string PAGINAWEB { get; set; }
        public int estadoFecEmi { get; set; }
        public string TIPOIDENTIFICACION { get; set; }
        public string VENDEDOR { get; set; }
        public string ENVIACORREO { get; set; }
        public string ERRORCORREO { get; set; }
        public byte[] clavebyte { get; set; }
        public string REGION { get; set; }
        public Nullable<double> SUBTOTALCERO { get; set; }
        public string ANULADO { get; set; }
    
        public virtual APEMPRESA APEMPRESA { get; set; }
    }
}
