//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODERN_GUI_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APOPERADOR
    {
        public int ID { get; set; }
        public int EMPRESA { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CEDULA { get; set; }
        public string CLAVE { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual APEMPRESA APEMPRESA { get; set; }
    }
}
