//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODERN_GUI_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRETENCION
    {
        public int ID { get; set; }
        public int EMPRESA { get; set; }
        public int SUCURSAL { get; set; }
        public string RUCRET { get; set; }
        public string NOMBRERET { get; set; }
        public string DIRECCIONRET { get; set; }
        public string TELEFONRET { get; set; }
        public string CORREORET { get; set; }
        public string SERIERET { get; set; }
        public long NUMERORET { get; set; }
        public string NOAUTORIZACION { get; set; }
        public Nullable<System.DateTime> FECHARET { get; set; }
        public string CLAVEACCESO { get; set; }
        public string ARCHIVOSOLO { get; set; }
        public string ARCHIVOFIRMA { get; set; }
        public string CONCEPTOERROR { get; set; }
        public string ARCHIVOERROR { get; set; }
        public string CODIGOERROR { get; set; }
        public string ARCHIVOAUTORIZACION { get; set; }
        public string ARCHIVOPDF { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public string HORAREGISTRO { get; set; }
        public Nullable<System.DateTime> FECHAPROCESO { get; set; }
        public string HORAPROCESO { get; set; }
        public string ESTADOPROCESO { get; set; }
        public string SUBIDOALAWEB { get; set; }
        public string ACTUALIZADOSC { get; set; }
        public string CODCLIENTE { get; set; }
        public string NombreDocumento { get; set; }
        public Nullable<int> estadoFecEmi { get; set; }
        public string TIPOIDENTIFICACION { get; set; }
        public string CLAVE { get; set; }
        public string ENVIACORREO { get; set; }
        public string ERRORCORREO { get; set; }
        public byte[] clavebyte { get; set; }
        public string REGION { get; set; }
        public string ANULADO { get; set; }
        public string SUBIRWEB { get; set; }
        public string TIPO { get; set; }
    
        public virtual APEMPRESA APEMPRESA { get; set; }
    }
}
