//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODERN_GUI_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRUTAARCHIVO
    {
        public int ID { get; set; }
        public int EMPRESA { get; set; }
        public string FACARCHIVOSOLO { get; set; }
        public string FACARCHIVOFIRMADO { get; set; }
        public string FACARCHIVOAUTORIZADO { get; set; }
        public string FACARCHIVOERROR { get; set; }
        public string FACPDF { get; set; }
        public string NCRARCHIVOSOLO { get; set; }
        public string NCRARCHIVOFIRMADO { get; set; }
        public string NCRARCHIVOAUTORIZADO { get; set; }
        public string NCRARCHIVOERROR { get; set; }
        public string NCRPDF { get; set; }
        public string GUIARCHIVOSOLO { get; set; }
        public string GUIARCHIVOFIRMADO { get; set; }
        public string GUIARCHIVOAUTORIZADO { get; set; }
        public string GUIARCHIVOERROR { get; set; }
        public string GUIAPDF { get; set; }
        public string RETARCHIVOSOLO { get; set; }
        public string RETARCHIVOFIRMADO { get; set; }
        public string RETARCHIVOAUTORIZADO { get; set; }
        public string RETARCHIVOERROR { get; set; }
        public string RETPDF { get; set; }
        public string NDBARCHIVOSOLO { get; set; }
        public string NDBARCHIVOFIRMADO { get; set; }
        public string NDBARCHIVOAUTORIZADO { get; set; }
        public string NDBARCHIVOERROR { get; set; }
        public string NDBPDF { get; set; }
    
        public virtual APEMPRESA APEMPRESA { get; set; }
    }
}
